CREATE TABLE users (
  user_id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  firstname VARCHAR(45),
  lastname VARCHAR(45),
  email  VARCHAR(100),
  username VARCHAR(45),
  password VARCHAR(100),
  enabled BOOLEAN
);

INSERT INTO users (firstname, lastname, email, username, password, enabled) 
VALUES ('firstname', 'lastname', 'admin@admin.com', 'admin', 'admin', true);
INSERT INTO users (firstname, lastname, email, username, password, enabled) 
VALUES ('user', 'user', 'user@user.com', 'user', '12345', true);